### ISSUE TITLE
Вакансия java разработчика

### ISSUE THREAD

**Issue by agolubenk** [ivanosh/QWERTYLed#1]
Добрый день! 
Меня зовут Андрей, рекрутер. 
Мы ищем специалиста на вакансию Java разработчика: 
- Middle: https://rabota.by/vacancy/51806143 
- Senior: https://rabota.by/vacancy/51806144 
- Tech-Lead: https://rabota.by/vacancy/51806147 

Интересно было ли Вам рассмотреть предложение?

**Comment by 3mph4515** [comment]
@agolubenk кек
